name: Update CSV daily

on:
  schedule:
    - cron: '0 5 * * *'  # elke dag om 05:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run fetch_prices.py
        run: python fetch_prices.py

      - name: Set git user config
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Show git remote and user
        run: |
          git remote -v
          git config --get user.name
          git config --get user.email

      - name: Commit and push CSV and log
        run: |
          git add output/
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m 'Update CSV and log [skip ci]'
            git push origin HEAD:main
          fi